DROP TABLE IF EXISTS SALES;
DROP TABLE IF EXISTS CATEGORIES;
DROP TABLE IF EXISTS Users;

CREATE TABLE CATEGORIES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category VARCHAR(100) NOT NULL UNIQUE
);

INSERT INTO CATEGORIES (category) VALUES ('paper');
INSERT INTO CATEGORIES (category) VALUES ('subscription');
INSERT INTO CATEGORIES (category) VALUES ('brochure');
INSERT INTO CATEGORIES (category) VALUES ('donation');
INSERT INTO CATEGORIES (category) VALUES ('other');

CREATE TABLE USERS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    branch VARCHAR(255)
);

INSERT INTO USERS (email, password, branch) VALUES ('admin', 'admin', '');

CREATE TABLE SALES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    categoryId INTEGER NOT NULL,
    userId INTEGER NOT NULL,
    amountSold INTEGER NOT NULL,
    revenue FLOAT NOT NULL,
    saledate DATE NOT NULL,
    note VARCHAR(255),
    FOREIGN KEY (categoryId) REFERENCES CATEGORIES(id),
    FOREIGN KEY (userId) REFERENCES USERS(id)
);

INSERT INTO SALES (categoryId, userId, amountSold, revenue, saledate, note)
    VALUES (1, 1, 3, 5.4, '2020-03-05', 'this is a note');